data_path: data/
results_save_path: results/
models_save_path: models/
dataset: 
  - name: nasa_cmapss
    type: run-to-failure
    train:
      - train_FD001.txt
    validation:
      - val_FD001.txt
    test:
      - test_FD001.txt
    early_train_split: 0.2
anticipation:
  - mode: fixed_deadline
    lead: 1
    horizon: 1
    steps: 10
prefix:
  max_length: 100
  min_length: 10
  stride: 20
cost:
  misclassification: [[0,1],[1,0]]
  delay: 
    type: linear
    slope: 0.1
  combination: 
    method: tradeoff
    alphas: [0.1, 0.3, 0.5, 0.7, 0.9]
early_classifiers:
  - path: aeon.classification.early_classification.ProbabilityThresholdEarlyClassifier
  - path: aeon.classification.early_classification.TEASER
  - path: earlywarn.early_classification.calimera
classifiers:
  - path: earlywarn.classification.prefix_ensemble.ProgressivePrefixEnsembleClassifier
    params:
      - base: aeon.classification.convolution_based.MiniRocketClassifier
      - alphas: [1.0e-03, 4.6e-03, 2.1e-02, 1e-01, 4.6e-01, 2.1e+00, 1e+01, 4.6e+01, 2e+02, 1e+03]
random_seed: 42